-- ============================================================
-- Run each file below in the Supabase SQL Editor in this order.
-- Every file is safe to re-run (IF NOT EXISTS / ON CONFLICT DO NOTHING).
--
-- Architecture note:
-- All admin writes go through app/api/* routes using the service
-- role key (SUPABASE_SECRET_KEY), which bypasses RLS entirely.
-- RLS write policies are only needed for client-side storage uploads.
-- ============================================================

-- 1.  storage/buckets.sql       — create storage buckets
-- 2.  admin/tables.sql          — admin_roles
-- 3.  admin/policies.sql        — RLS + grants + policies for admin_roles
-- 4.  photos/tables.sql         — photos table + display_order constraint
-- 5.  photos/policies.sql       — RLS + grants + policies for photos
-- 6.  photos/functions.sql      — reorder_photo RPC
-- 7.  resume/tables.sql         — resume table
-- 8.  resume/policies.sql       — RLS + grants + policies for resume
-- 9.  guitar-tabs/tables.sql    — guitar_tabs (legacy) + genres/tunings/artists/songs/tabs
-- 10. guitar-tabs/policies.sql  — RLS + grants + policies for all guitar-tabs tables
-- 11. storage/policies.sql      — storage object policies (guitar-tabs bucket)
